#
# Makefile - xcode project templates
# Copyright (C) 2016 Heiko Abraham
# All rights reserved. 🍪⚙🏛✅
#


DEST_DIR=$(HOME)/Library/Developer/Xcode/Templates/Cortex-M
TEMPLATE_SRC=../templates
COMPILER_RT_SRC=$(COMPILER_RT_VERSION).src/lib/builtins/arm


include Makefile.def


.PHONY: build
build: clean
	@echo "destination : $(DEST_DIR)"
	$(MKDIR) -p $(DEST_DIR)/CrossPlatformCortexM.xctemplate
	cp $(TEMPLATE_SRC)/CrossPlatformCortexM.xctemplate/TemplateInfo.plist \
		$(DEST_DIR)/CrossPlatformCortexM.xctemplate
	$(MKDIR) -p $(DEST_DIR)/Static\ Library.xctemplate
	cp $(TEMPLATE_SRC)/Static\ Library.xctemplate/TemplateIcon*png \
		$(DEST_DIR)/Static\ Library.xctemplate
	cp $(TEMPLATE_SRC)/Static\ Library.xctemplate/TemplateInfo.plist \
		$(DEST_DIR)/Static\ Library.xctemplate
	$(MKDIR) -p $(DEST_DIR)/Bare\ Metal.xctemplate/bsp/linker
	$(MKDIR) -p $(DEST_DIR)/Bare\ Metal.xctemplate/bsp/sign
	$(MAKE) -f $(MAKEFILENAME) compiler_rt
	cp $(TEMPLATE_SRC)/Bare\ Metal.xctemplate/TemplateIcon*png \
		$(DEST_DIR)/Bare\ Metal.xctemplate
	cp $(TEMPLATE_SRC)/Bare\ Metal.xctemplate/TemplateInfo.plist \
		$(DEST_DIR)/Bare\ Metal.xctemplate
	cp $(TEMPLATE_SRC)/Bare\ Metal.xctemplate/Makefile \
		$(DEST_DIR)/Bare\ Metal.xctemplate
	cp $(TEMPLATE_SRC)/Bare\ Metal.xctemplate/main.c \
		$(DEST_DIR)/Bare\ Metal.xctemplate
	cp $(TEMPLATE_SRC)/Bare\ Metal.xctemplate/bsp/sign/none.entitlements \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/sign
	cp $(TEMPLATE_SRC)/Bare\ Metal.xctemplate/bsp/linker/*.ld \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/linker


# add compiler_rt for Cortex-M3/M4
compiler_rt:
	$(MKDIR) -p $(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	echo "origin source for this directory, LLVM $(COMPILER_RT_VERSION)" \
		> $(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/readme.txt
	rm -rf temp_compiler_rt
	$(MKDIR) temp_compiler_rt
	tar -xJf $(DOWNLOAD_DIR)/$(COMPILER_RT_VERSION).tar.xz -C temp_compiler_rt
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/aeabi_dcmp.S \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/aeabi_div0.c \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/aeabi_drsub.c \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/aeabi_fcmp.S \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/aeabi_frsub.c \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/aeabi_idivmod.S \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/aeabi_ldivmod.S \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/aeabi_uidivmod.S \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/aeabi_uldivmod.S \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/divmodsi4.S \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/udivmodsi4.S \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt/arm
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/../assembly.h \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/../fp_lib.h \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/../int_lib.h \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/../int_types.h \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/../int_endianness.h \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt
	cp temp_compiler_rt/$(COMPILER_RT_SRC)/../int_util.h \
		$(DEST_DIR)/Bare\ Metal.xctemplate/bsp/compiler_rt
	rm -rf temp_compiler_rt



.PHONY: clean
clean:
	$(RM) -rf $(DEST_DIR)
