#
# Makefile - global makefile defines
# Copyright (C) 2015-2017 Heiko Abraham
# All rights reserved.
#

# current working directory
CURRENT_DIR:=$(shell pwd)
OS_TYPE=$(shell uname -s)

ifeq ($(OS_TYPE),Darwin)
CURRENT_ARCH := x86_64
else
CURRENT_ARCH := $(shell uname -i)
endif


#
# get makefile name
#
ifeq ($(MAKEFILENAME),)
MAKEFILENAME := $(firstword $(MAKEFILE_LIST))
endif

#
# detect number of CPUs usable for make jobs
#
NUM_CPUS=4
ifeq ($(OS_TYPE),Darwin)
  NUM_CPUS=$(shell sysctl -n hw.ncpu)
endif
ifeq ($(OS_TYPE),Linux)
  NUM_CPUS=$(shell grep ^processor /proc/cpuinfo|wc -l)
endif
MJOBS=-j$(NUM_CPUS)

RM=/bin/rm
MKDIR=/bin/mkdir


#
# define project directories
#
DOWNLOAD_DIR:=../download-cache
BUILD_DIR:=$(CURRENT_DIR)/../builddir
PREFIX_HOST:=$(BUILD_DIR)/usr-host
ifeq ($(CVER),)
  CVER:=1.8.1
endif
DEST_PREFIX:=/usr/local
ifneq ($(INST_PREFIX),)
  DEST_PREFIX:=$(INST_PREFIX)
endif
PREFIX:=$(BUILD_DIR)/$(DEST_PREFIX)

#
# prepend own tools to path
#
PATH_EXT=PATH=$(PREFIX_HOST)/bin:$(PREFIX)/bin:$(PATH)


#
# define source versions
#
BINUTIL_VERSION_NO:=2.28
BINUTIL_VERSION:=binutils-$(BINUTIL_VERSION_NO)

CMAKE_VERSION_NO:=3.5.2
CMAKE_VERSION:=cmake-$(CMAKE_VERSION_NO)

LLVM_VERSION_NO:=4.0.0
LLVM_VERSION:=llvm-$(LLVM_VERSION_NO)
CLANG_VERSION:=cfe-$(LLVM_VERSION_NO)
COMPILER_RT_VERSION:=compiler-rt-$(LLVM_VERSION_NO)
LLDB_VERSION:=lldb-$(LLVM_VERSION_NO)


all: build


$(PREFIX)/:
	$(MKDIR) -p $(PREFIX)/

$(BUILD_DIR)/:
	$(MKDIR) -p $(BUILD_DIR)/

.PHONY: clean_build_dir
clean_build_dir:
	$(RM) -rf $(BUILD_DIR)/
