#
# Makefile - clean all
# Copyright (C) 2016 Heiko Abraham
# All rights reserved.
#

include Makefile.def

.PHONY: build
build:


.PHONY: clean
clean:
	$(RM) -rf $(BUILD_DIR)


.PHONY: install
install:
