#
# Makefile - global makefile defines
# Copyright (C) 2015-2016 Heiko Abraham
# All rights reserved.
#

# current working directory
CURRENT_DIR:=$(shell pwd)

ifeq ($(MAKEFILENAME),)
MAKEFILENAME := $(firstword $(MAKEFILE_LIST))
endif

# detect number of CPUs usable for make jobs
NUM_CPUS=$(shell sysctl -n hw.ncpu)
MJOBS=-j$(NUM_CPUS)

RM=rm

DOWNLOAD_DIR=$(PROJECT_DIR)/download-cache


BINUTIL_VERSION_NO:=2.27
BINUTIL_VERSION:=binutils-$(BINUTIL_VERSION_NO)

CMAKE_VERSION_NO:=3.5.2
CMAKE_VERSION:=cmake-$(CMAKE_VERSION_NO)

XZ_VERSION_NO:=5.0.4
XZ_VERSION:=xz-$(XZ_VERSION_NO)

LLVM_VERSION_NO:=3.8.1
LLVM_VERSION:=llvm-$(LLVM_VERSION_NO)
CLANG_VERSION:=cfe-$(LLVM_VERSION_NO)
COMPILER_RT_VERSION:=compiler-rt-$(LLVM_VERSION_NO)
LLDB_VERSION:=lldb-$(LLVM_VERSION_NO)
